# Generated by Django 6.0.2 on 2026-02-18 05:48

import django.db.models.deletion
import django.utils.timezone
import ota.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gatewayconfig_created_at_and_more'),
        ('ota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTargetedFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this target is still active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Targeted Firmware',
                'verbose_name_plural': 'Device Targeted Firmwares',
            },
        ),
        migrations.CreateModel(
            name='TargetedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('single', 'Single Device'), ('multiple', 'Multiple Devices'), ('version_based', 'Version Based')], max_length=20)),
                ('source_version', models.CharField(blank=True, help_text='Current firmware version to target (for version-based updates)', max_length=32, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('devices_total', models.PositiveIntegerField(default=0)),
                ('devices_updated', models.PositiveIntegerField(default=0)),
                ('devices_failed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='deviceupdatelog',
            new_name='ota_deviceu_device__dccc52_idx',
            old_name='ota_deviceu_device_2a7a8b_idx',
        ),
        migrations.RenameIndex(
            model_name='deviceupdatelog',
            new_name='ota_deviceu_status_5e9474_idx',
            old_name='ota_deviceu_status_8f3c4d_idx',
        ),
        migrations.AlterField(
            model_name='firmwareversion',
            name='file',
            field=models.FileField(help_text='Firmware binary file', storage=ota.models.FirmwareStorage(), upload_to='firmware/'),
        ),
        migrations.AddField(
            model_name='devicetargetedfirmware',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_firmware', to='api.device'),
        ),
        migrations.AddField(
            model_name='devicetargetedfirmware',
            name='target_firmware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ota.firmwareversion'),
        ),
        migrations.AddField(
            model_name='targetedupdate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_updates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='targetedupdate',
            name='target_devices',
            field=models.ManyToManyField(blank=True, related_name='targeted_updates', to='api.device'),
        ),
        migrations.AddField(
            model_name='targetedupdate',
            name='target_firmware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_updates', to='ota.firmwareversion'),
        ),
        migrations.AddField(
            model_name='devicetargetedfirmware',
            name='targeted_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_targets', to='ota.targetedupdate'),
        ),
    ]
