# Generated by Django 6.0.2 on 2026-02-18 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gatewayconfig_created_at_and_more'),
        ('ota', '0002_devicetargetedfirmware_targetedupdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetargetedfirmware',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this target is still active'),
        ),
        migrations.AlterField(
            model_name='firmwareversion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Only active versions are offered to devices'),
        ),
        migrations.AlterField(
            model_name='targetedupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='devicetargetedfirmware',
            index=models.Index(fields=['is_active'], name='ota_devicet_is_acti_3c2331_idx'),
        ),
        migrations.AddIndex(
            model_name='firmwareversion',
            index=models.Index(fields=['is_active', '-created_at'], name='ota_firmwar_is_acti_2e0902_idx'),
        ),
        migrations.AddIndex(
            model_name='targetedupdate',
            index=models.Index(fields=['status', '-created_at'], name='ota_targete_status_081af5_idx'),
        ),
    ]
