# Generated by Django 5.2.7 on 2025-11-18 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_serial", models.CharField(max_length=64, unique=True)),
                (
                    "public_key_algorithm",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("csr_pem", models.TextField(blank=True, null=True)),
                (
                    "provisioned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "config_version",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GatewayConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_id", models.CharField(max_length=64, unique=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("config_schema_ver", models.PositiveIntegerField(default=1)),
                ("baud_rate", models.PositiveIntegerField(default=9600)),
                ("data_bits", models.PositiveSmallIntegerField(default=8)),
                ("stop_bits", models.PositiveSmallIntegerField(default=1)),
                ("parity", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SlaveDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slave_id", models.PositiveSmallIntegerField()),
                ("device_name", models.CharField(max_length=64)),
                ("polling_interval_ms", models.PositiveIntegerField(default=5000)),
                ("timeout_ms", models.PositiveIntegerField(default=1000)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "gateway_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slaves",
                        to="api.gatewayconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["slave_id"],
                "unique_together": {("gateway_config", "slave_id")},
            },
        ),
        migrations.CreateModel(
            name="RegisterMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("address", models.PositiveIntegerField()),
                ("num_registers", models.PositiveSmallIntegerField(default=1)),
                ("function_code", models.PositiveSmallIntegerField(default=3)),
                ("data_type", models.PositiveSmallIntegerField(default=0)),
                ("scale_factor", models.FloatField(default=1.0)),
                ("offset", models.FloatField(default=0.0)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "slave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registers",
                        to="api.slavedevice",
                    ),
                ),
            ],
            options={
                "ordering": ["address"],
            },
        ),
        migrations.CreateModel(
            name="TelemetryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("data_type", models.CharField(max_length=64)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=16, null=True)),
                ("slave_id", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "register_label",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("quality", models.CharField(default="good", max_length=16)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="api_telemet_device__5343fd_idx",
                    ),
                    models.Index(
                        fields=["data_type"], name="api_telemet_data_ty_7c6567_idx"
                    ),
                ],
            },
        ),
    ]
