# Generated by Django 5.2.8 on 2025-11-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_device_user_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewayconfig",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
