# Generated by Django 6.0.2 on 2026-02-04 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_alter_device_user_device_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('device_offline', 'Device Offline'), ('low_battery', 'Low Battery'), ('high_temperature', 'High Temperature'), ('communication_error', 'Communication Error'), ('threshold_exceeded', 'Threshold Exceeded'), ('maintenance_due', 'Maintenance Due'), ('custom', 'Custom')], max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.device')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='api_alert_device__ef9260_idx'), models.Index(fields=['severity', 'status'], name='api_alert_severit_548a52_idx'), models.Index(fields=['triggered_at'], name='api_alert_trigger_282cf1_idx')],
            },
        ),
    ]
