# Generated by Django 6.0.2 on 2026-02-18 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gatewayconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
