# Generated by Django 5.1.9 on 2026-02-12 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_comprehensive_modbus_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceOTAStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("downloading", "Downloading"),
                            ("installing", "Installing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        default=0, help_text="Download/install progress"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("previous_version", models.CharField(blank=True, max_length=50)),
                ("target_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device OTA Status",
                "verbose_name_plural": "Device OTA Statuses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTAUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(max_length=50)),
                (
                    "firmware_file",
                    models.FileField(max_length=255, upload_to="ota_updates/"),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "checksum",
                    models.CharField(
                        blank=True, help_text="SHA256 checksum", max_length=128
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Device"),
                            ("group", "Device Group"),
                            ("all", "All Devices"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Criteria for automatic device selection",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_devices", models.PositiveIntegerField(default=0)),
                ("successful_updates", models.PositiveIntegerField(default=0)),
                ("failed_updates", models.PositiveIntegerField(default=0)),
                ("pending_updates", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OTA Update",
                "verbose_name_plural": "OTA Updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="registermapping",
            new_name="api_registe_slave_i_584373_idx",
            old_name="api_registermapping_slave_addr_idx",
        ),
        migrations.RenameIndex(
            model_name="registermapping",
            new_name="api_registe_enabled_1208aa_idx",
            old_name="api_registermapping_enabled_idx",
        ),
        migrations.AddField(
            model_name="device",
            name="firmware_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="last_heartbeat",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="memory_usage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="uptime_seconds",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="device",
            name="wifi_rssi",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gatewayconfig",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="gatewayconfig",
            name="data_bits",
            field=models.PositiveSmallIntegerField(
                choices=[(7, "7 bits"), (8, "8 bits")], default=8
            ),
        ),
        migrations.AlterField(
            model_name="gatewayconfig",
            name="stop_bits",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1 bit"), (2, "2 bits")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="gatewayconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="deviceotastatus",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ota_statuses",
                to="api.device",
            ),
        ),
        migrations.AddField(
            model_name="otaupdate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ota_updates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otaupdate",
            name="target_devices",
            field=models.ManyToManyField(
                blank=True, help_text="Specific devices to target", to="api.device"
            ),
        ),
        migrations.AddField(
            model_name="otaupdate",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ota_updates_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deviceotastatus",
            name="ota_update",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_statuses",
                to="api.otaupdate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deviceotastatus",
            unique_together={("ota_update", "device")},
        ),
    ]
