# Generated by Django 5.2.11 on 2026-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_deviceotastatus_otaupdate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otaupdate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="otaupdate",
            name="target_devices",
        ),
        migrations.RemoveField(
            model_name="otaupdate",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="device",
            name="firmware_version",
        ),
        migrations.RemoveField(
            model_name="device",
            name="is_online",
        ),
        migrations.RemoveField(
            model_name="device",
            name="last_heartbeat",
        ),
        migrations.RemoveField(
            model_name="device",
            name="memory_usage",
        ),
        migrations.RemoveField(
            model_name="device",
            name="uptime_seconds",
        ),
        migrations.RemoveField(
            model_name="device",
            name="wifi_rssi",
        ),
        migrations.AlterField(
            model_name="gatewayconfig",
            name="data_bits",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="gatewayconfig",
            name="stop_bits",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="DeviceOTAStatus",
        ),
        migrations.DeleteModel(
            name="OTAUpdate",
        ),
    ]
