# Generated by Django 6.0.2 on 2026-02-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_created_at_auto_now_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermapping',
            name='access_mode',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='byte_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='decimal_places',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='high_alarm_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='low_alarm_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='register_type',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='unit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='registermapping',
            name='word_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slavedevice',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
