# Generated by Django 5.2.11 on 2026-02-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_otaupdate_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="gateway_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="api.gatewayconfig",
            ),
        ),
    ]
