# Generated by Django 5.2.11 on 2026-02-13 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_add_gateway_config_to_device"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="slavedevice",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="gatewayconfig",
            name="slaves",
            field=models.ManyToManyField(
                blank=True, related_name="presets", to="api.slavedevice"
            ),
        ),
        migrations.AddField(
            model_name="slavedevice",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="slavedevice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="slavedevice",
            name="gateway_config",
        ),
    ]
