# Generated by Django 5.2.11 on 2026-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_user_type_to_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="mac_address",
            field=models.CharField(
                blank=True,
                help_text="Hardware MAC address (format: AA:BB:CC:DD:EE:FF)",
                max_length=17,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_serial",
            field=models.CharField(
                help_text="Internal device ID for API communication",
                max_length=64,
                unique=True,
            ),
        ),
    ]
