# Generated by Django 6.0.2 on 2026-02-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_owner_device_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity_kw', models.FloatField()),
                ('tilt_deg', models.FloatField(default=18.0)),
                ('azimuth_deg', models.FloatField(default=180.0)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_solarsite',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='hw_id',
            field=models.CharField(blank=True, help_text='MAC address or hardware ID sent at provisioning', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, help_text='Device model string sent at provisioning', max_length=64, null=True),
        ),
    ]
