# Generated by Django 6.0.2 on 2026-02-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_device_status_logs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicelog',
            new_name='api_devicel_device__6d2e3e_idx',
            old_name='api_devicel_device__idx',
        ),
        migrations.RenameIndex(
            model_name='devicelog',
            new_name='api_devicel_log_lev_4ee3db_idx',
            old_name='api_devicel_log_lev_idx',
        ),
        migrations.AddField(
            model_name='device',
            name='config_ack_ver',
            field=models.PositiveIntegerField(blank=True, help_text='Last config version acknowledged by device via /configAck', null=True),
        ),
        migrations.AddField(
            model_name='gatewayconfig',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Incremented on every config or slave change — used for cfgVer in device protocol'),
        ),
    ]
