# Generated by Django 5.2.11 on 2026-02-27 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_device_pending_rollback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["user"], name="api_device_user_id_ce916f_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["config_version"], name="api_device_config__c26c30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["last_heartbeat"], name="api_device_last_he_56cbdd_idx"
            ),
        ),
    ]
