# Generated by Django 5.2.11 on 2026-02-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_device_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=64)),
                ("timestamp", models.DateTimeField()),
                (
                    "payload",
                    models.JSONField(
                        help_text="Full Deye inverter payload as received from device"
                    ),
                ),
                (
                    "dynamo_ok",
                    models.BooleanField(
                        default=False, help_text="Written to DynamoDB successfully"
                    ),
                ),
                (
                    "s3_ok",
                    models.BooleanField(
                        default=False, help_text="Written to S3 CSV successfully"
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_telemetry",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(
                        fields=["site_id", "-timestamp"],
                        name="api_telemet_site_id_b57131_idx",
                    ),
                    models.Index(
                        fields=["dynamo_ok", "s3_ok", "received_at"],
                        name="api_telemet_dynamo__92c02e_idx",
                    ),
                ],
            },
        ),
    ]
