# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_telemetry_raw"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryMessageId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_message_ids",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-first_seen_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="telemetrymessageid",
            constraint=models.UniqueConstraint(
                fields=("device", "message_id"),
                name="api_telemetrymessageid_device_message_id_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="telemetrymessageid",
            index=models.Index(
                fields=["first_seen_at"],
                name="api_telemetrymessageid_first_seen_at_idx",
            ),
        ),
    ]
